server:
  port: 8080

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.seu.scrm.Entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.159.104.30:3306/scrm?serverTimezone=GMT%2B8
    username: root
    password: SCRMbd3162.
redis:
  host: 127.0.0.1
  port: 6379
  pool:
      max-active: -1
      max-wait: 1
      max-idle: 8
      min-idle: 0
  timeout: 1000